# specify docker file version
version: "3"
# define list of services 
services:
  # define myportfolio service
  pe-portfolio-site:
    container_name: pe-portfolio-site
    # define service will b e built with dockerfile in current directory
    build: .
    # restart on reboot or error
    restart: always
    # define file containing enviornment variables
    env_file:
      - .env
    ports:
      - 5000:5000
    # specify container should start after mysql service is up
    depends_on:
      - mysql
  
  # define mysql service
  mysql:
    container_name: mysql
    # lower resource usage than mysql
    image: mariadb
    # restart on error or reboot
    restart: always
    # define file containing enviornemnt variables
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
  
  # define nginx container
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    # generates certificates
    environment:
      - CERTBOT_EMAIL=gino.rey@outlook.com
    # bind ports to the internet
    ports:
      - 80:80
      - 443:443
    # store certificate files in a volume
    volumes:
      - nginx_secrets:/etc/letsencrypt
      # map config files into the container
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - pe-portfolio-site
# define a volume that will persist if containers are recreated
volumes:
  mydatabase:
  nginx_secrets:
